package app.kejian.mobile

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.TextUnit

/** The persisted UI language. User-entered course content is never translated. */
object AppLanguage {
    /** Snapshot state makes every visible Compose surface recompose immediately after a language change. */
    var code:String by mutableStateOf("zh")
    val english get()=code=="en"
}

private val exactEnglish=mapOf(
    "课间" to "Kejian", "课表" to "Schedule", "识别" to "AI", "录音" to "Record", "小组件" to "Widgets", "设置" to "Settings",
    "今天" to "Today", "明天" to "Tomorrow", "上一周" to "Previous week", "下一周" to "Next week", "列表" to "List",
    "编辑" to "Edit", "保存" to "Save", "新建" to "New", "取消" to "Cancel", "删除" to "Delete", "复制" to "Duplicate", "自定义" to "Customize",
    "停止" to "Stop", "需要" to "Required", "失败" to "Failed", "错误" to "Error", "无效" to "Invalid", "云" to "Cloud", "锁" to "Locked", "课" to "events",
    "知道了" to "Got it", "返回" to "Back", "开始使用" to "Get started", "下一步" to "Next", "上一步" to "Back", "跳过" to "Skip",
    "表格编辑" to "Table editor", "↶ 撤销" to "↶ Undo", "↷ 重做" to "↷ Redo", "未保存的草稿" to "Unsaved draft", "编辑课表" to "Edit schedule",
    "所有周次 ⇄" to "All weeks ⇄", "仅本次 ⇄" to "This one ⇄", "批量删除" to "Batch delete", "退出框选" to "Exit selection",
    "本周课程" to "This week", "本周暂无课程，点击新建开始安排。" to "Nothing scheduled this week. Tap New to begin.",
    "轻触空白处收起" to "Tap outside to close", "地点" to "Location", "教师" to "Teacher",
    "按你的节奏" to "At your pace", "外观" to "Appearance", "跟随系统" to "System", "浅色" to "Light", "深色" to "Dark",
    "页面、文字、按钮、课程和小组件同步适配。" to "Pages, text, controls, events and widgets adapt together.",
    "语言 / Language" to "Language", "中文" to "Chinese", "English" to "English",
    "学期设置" to "Term settings", "学期名称" to "Term name", "第一周的周一 · YYYY-MM-DD" to "Monday of week 1 · YYYY-MM-DD",
    "改变学期起点会重新计算重复课日期；已单独调整的课程保留原日期。" to "Changing the term start recalculates recurring dates. Individually adjusted events keep their dates.",
    "保存学期" to "Save term", "课前提醒" to "Event reminders", "通知权限已允许" to "Notifications allowed", "需要允许系统通知" to "Notifications required",
    "提前多久发送" to "Notify before", "允许准时提醒" to "Allow exact reminders", "打开系统通知设置" to "Open notification settings",
    "启用弹窗提醒" to "Enable banners", "横幅渠道设置" to "Banner settings", "发送测试通知" to "Send test notification",
    "使用引导" to "Guide", "重看交互教学" to "Replay interaction guide", "安装已下载更新" to "Install downloaded update", "后台下载更新" to "Download update in background",
    "本月 AI 积分" to "AI credits this month", "无限" to "Unlimited", "未登录" to "Not signed in", "默认用户" to "Standard user",
    "登录后可管理账号与云存档。" to "Sign in to manage your account and cloud saves.",
    "支持者已开放多个云存档与小组件背景。" to "Supporter includes multiple cloud saves and widget backgrounds.",
    "桌面上的小课表" to "Your schedule at a glance", "只看未来 24 小时，从容安排。" to "See the next 24 hours and plan with ease.",
    "支持者背景" to "Supporter backgrounds", "开发者" to "Developer", "会员已开放" to "Membership active", "纯色" to "Solid", "半透明" to "Translucent", "图片" to "Image",
    "背景不透明度" to "Background opacity", "只改变背景透明度，文字和彩色标签始终保持清晰。" to "Only the background changes opacity; text and color tags stay crisp.",
    "选择背景图片" to "Choose background image", "更换背景图片" to "Change background image", "背景明暗" to "Image brightness", "原图" to "Original",
    "图片只保存在本机；调整明暗可以让课程文字更容易辨认。" to "The image stays on this device. Adjust brightness to keep event text readable.",
    "支持者外观权益" to "Supporter appearance", "圆角与文字留白" to "Corners and text padding", "调整圆角与边距" to "Adjust corners and padding",
    "圆角大小" to "Corner radius", "文字内边距" to "Text padding", "上边距" to "Top", "下边距" to "Bottom", "左边距" to "Left", "右边距" to "Right",
    "恢复默认" to "Restore defaults", "应用到小组件" to "Apply to widgets", "桌面列表找不到课间？" to "Can't find Kejian in the widget list?",
    "课程名称" to "Event name", "课堂地址" to "Location", "教室 · 选填" to "Room · optional", "老师 · 选填" to "Host / teacher · optional", "课程颜色" to "Event color",
    "例如：东校区 · 博学楼 / 具体街道地址" to "For example: East Campus · Science Building / street address",
    "可填写校区、楼栋或具体地址；会显示在课前提醒中" to "Add a campus, building or street address. It will appear in reminders.",
    "时长（分钟）" to "Duration (minutes)", "上课星期" to "Day", "重复周次" to "Repeat weeks", "单周" to "Odd weeks", "双周" to "Even weeks",
    "上下滚动可精确到任意分钟；只有拖动模块时按半小时吸附。" to "Scroll to any exact minute. Only drag placement snaps to half-hour intervals.",
    "1-16 或 1,3,5；支持第 1–30 周" to "1-16 or 1,3,5 · weeks 1–30 are supported",
    "提前时间可在设置中自由调整" to "Choose the lead time in Settings",
    "先加入草稿，回到课表点保存后生效。" to "This enters the draft first. Return to the schedule and tap Save to apply it.",
    "删除课程" to "Delete event", "完成自定义" to "Save changes", "确定创建" to "Create event", "删除这节课？" to "Delete this event?",
    "编辑课程" to "Edit event", "新建课程" to "New event", "把时间留给重要的事。" to "Keep time for what matters.",
    "新建截止日" to "New deadline", "编辑截止日" to "Edit deadline", "截止日名称" to "Deadline title", "截止日期" to "Due date", "截止时间" to "Due time",
    "详细说明 · 选填" to "Details · optional", "关联课程 · 选填" to "Related event · optional", "不关联课程" to "No related event", "删除截止日" to "Delete deadline",
    "截止日按日期标记整列，不会挤进凌晨的时间轴。" to "A deadline is marked on its date and never squeezed into the midnight timeline.",
    "例如：线性代数作业" to "For example: Linear algebra assignment", "关联课程 · 可不关联" to "Related event · optional", "独立截止日" to "Standalone deadline",
    "标记颜色" to "Marker color", "截止提醒" to "Deadline reminder", "按截止时间提醒；未填写时间时在当天 09:00 提醒" to "Uses the due time, or 9:00 AM on that date when no time is set.",
    "删除这个截止日？" to "Delete this deadline?", "确定" to "Confirm",
    "保存截止日" to "Save deadline",
    "导入课表" to "Import schedule", "从文件或 Excel 开始" to "Start from a file or spreadsheet", "选择文件" to "Choose file", "也可以粘贴表格" to "Or paste a table",
    "读取剪贴板" to "Read clipboard", "填入示例" to "Use example", "识别并预览" to "Parse and preview", "图片与 Office 文件" to "Images and Office files",
    "导入预览" to "Import preview", "识别提示" to "Recognition notes", "确认并应用" to "Confirm and apply", "恢复完整备份" to "Restore full backup",
    "课间 AI" to "Kejian AI", "只执行日程任务 · 所有结果先预览" to "Schedule tasks only · every result is previewed", "开通会员" to "Membership", "登录" to "Sign in",
    "发送" to "Send", "上传图片" to "Upload image", "描述课程或截止日任务…" to "Describe an event or deadline task…", "会员权益" to "Membership",
    "可以发送课表截图，或用一句话新增、替换、删除课程。所有改动都会先预览。" to "Send a schedule screenshot or add, replace or delete events in one sentence. Every change is previewed first.",
    "可以发送课表截图，或用一句话新增、替换、删除课程与截止日。所有改动都会先预览。" to "Send a schedule screenshot or add, replace or delete events and deadlines in one sentence. Every change is previewed first.",
    "已上传一张课表图片" to "Uploaded a schedule image", "已生成识别预览，请核对后确认。" to "The recognition preview is ready. Check it before confirming.",
    "任务已生成预览，请确认是否应用。" to "The task preview is ready. Confirm to apply it.", "AI 暂时没有返回有效课表，本次不计入额度" to "AI did not return a valid schedule. No credit was used.",
    "选择文件" to "Choose file", "变更预览" to "Change preview", "忽略无法识别的内容，仅导入有效课程" to "Skip unrecognized content and import valid events only",
    "成为支持者" to "Become a Supporter", "支持者会员" to "Supporter membership", "支付接入完成后开放购买。" to "Purchases will open after payment integration is complete.",
    "每个会员周期 30 积分，可用于图片识别和课表任务；确认应用有效结果时扣 1 积分。" to "Each membership cycle includes 30 credits for image recognition and schedule tasks. One credit is used only after you apply a valid result.",
    "同时开放 3 个云存档槽位，以及小组件半透明、图片背景和明暗调节。" to "Also includes three cloud save slots plus translucent and image widget backgrounds with brightness controls.",
    "开发者账号：全部权益已开放，AI 积分无限。" to "Developer account: all features are unlocked with unlimited AI credits.",
    "课间账号" to "Kejian account", "云端课表" to "Cloud schedule", "账号不是使用课间的前提" to "An account is optional", "创建账号" to "Create account",
    "邮箱" to "Email", "密码" to "Password", "创建账号并同步" to "Create and sync", "登录并同步" to "Sign in and sync", "从相册更换头像" to "Change avatar from Photos",
    "8–72 位，同时包含字母和数字" to "8–72 characters with both letters and numbers",
    "当前不发送邮箱验证码，也不要求绑定手机号。请确认邮箱拼写正确；忘记密码功能将在邮箱验证上线后提供。" to "Email verification and phone binding are not required yet. Check the spelling carefully; password recovery will arrive with email verification.",
    "继续即表示你已阅读《隐私政策》" to "By continuing, you confirm that you have read the Privacy Policy.",
    "长按并拖动存档完成上传或下载。只有目标已有内容、会发生覆盖时才会询问。" to "Hold and drag a save to upload or download it. Kejian asks only when existing data would be replaced.",
    "刷新云存档" to "Refresh cloud saves", "退出账号" to "Sign out", "注销账号并删除云端课表" to "Delete account and cloud data", "本地存档" to "Local save",
    "确认覆盖存档？" to "Replace this save?", "确认覆盖" to "Replace", "机器人验证码" to "Bot verification", "换一张" to "Refresh", "当前密码" to "Current password", "永久删除" to "Delete permanently",
    "先浏览，再编辑" to "Browse first, edit when ready", "从加号拖出一节课" to "Drag a new event from +", "点一下，浮起操作菜单" to "Tap once for quick actions",
    "拖到这里，松手删除" to "Drag here and release to delete", "框选多节，一次删除" to "Select several events at once", "按方向缩放，最后保存" to "Pinch by direction, then save",
    "把截止日放在日期上" to "Put deadlines on their dates", "让 AI 安全处理课表" to "Let AI handle schedules safely", "认识课间" to "Meet Kejian",
    "录音与课堂总结" to "Recording & summaries", "录音始终先保存在本机。只有你主动转写时才临时上传，处理结束立即删除服务器副本。" to "Recordings start and stay on this device. They are uploaded temporarily only when you request transcription, and the server copy is deleted as soon as processing ends.",
    "转写总结不限时" to "Unlimited transcription", "可录音与关联；转写总结需 Plus" to "Record and attach for free · transcription requires Plus", "准备好后轻触开始" to "Tap when you are ready", "正在记录课堂" to "Recording", "录音已完成" to "Recording complete",
    "选择课程模块" to "Choose an event", "选择关联课程" to "Attach to an event", "转写并总结" to "Transcribe & summarize", "处理中" to "Processing", "仅保存录音" to "Save recording only", "导出到手机文件夹" to "Export to a folder", "删除本地录音" to "Delete local audio",
    "AI 课堂总结" to "AI summary", "重点" to "Key points", "待办" to "Action items", "同时保留本地音频（不会上传云端）" to "Keep the original audio on this device", "保存为独立录音笔记" to "Save as an independent note", "最近的录音与总结" to "Recent recordings & summaries", "独立录音笔记" to "Independent recording note", "逐字稿" to "Transcript", "完成" to "Done",
    "普通用户" to "Standard", "登录" to "Sign in", "下一步" to "Next",
    "这是演示，不会修改你的课程。" to "This demo will not change your schedule.", "重播动画" to "Replay animation",
    "课表截图" to "Schedule image", "变更预览 · 3 节课" to "Change preview · 3 events", "确认后才会放入课表" to "Added only after you confirm", "创建截止日" to "Create deadline",
    "发现时间冲突" to "Time conflict found", "仍然保留" to "Keep anyway", "返回修改" to "Go back", "清空课表？" to "Clear schedule?", "确认清空" to "Clear",
    "添加到课间" to "Add to Kejian", "把课表安全留在云端？" to "Keep your schedule safely in the cloud?", "登录或创建账号" to "Sign in or create an account", "暂时不用" to "Not now",
    "打开通知设置" to "Open notification settings", "开始" to "Start", "结束" to "End", "星期" to "Day", "课程" to "Event", "教室" to "Room", "选择" to "Select",
    "课程时间" to "Event time", "清空，保持原时间" to "Clear and keep original time", "开始时间" to "Start time", "结束时间" to "End time",
    "当前使用清晰纯色背景。圆角与文字边距仍可免费调整。" to "A crisp solid background is active. Corners and text padding remain freely adjustable.",
    "半透明材质、自选背景图片和背景明暗调节属于支持者会员权益；圆角和文字边距始终免费。" to "Translucency, custom images and brightness controls are Supporter features. Corners and padding remain free.",
    "支持者会员 · ¥9.9 / 月" to "Supporter · ¥9.9 / month", "让四角更自然，文字离边缘更从容。设置应用到所有已添加的小组件。" to "Shape the corners and give text more breathing room. Changes apply to every added widget.",
    "支持 1 × 2、2 × 1、2 × 2、2 × 4 和 4 × 2。实际格数由手机桌面网格决定，添加后可长按调整大小。添加成功后课间会明确提示。" to "Supports 1 × 2, 2 × 1, 2 × 2, 2 × 4 and 4 × 2. The launcher decides the final grid size; hold the widget to resize it. Kejian confirms when it is added.",
    "先打开一次课间，再回到桌面搜索“小组件”。小米等部分系统若启用了应用锁、手机分身或隐私空间，桌面可能隐藏第三方组件；把课间安装在主空间、关闭对应限制并重启桌面后再试。" to "Open Kejian once, then search Widgets from the home screen. Some launchers hide third-party widgets when App Lock, Dual Apps or Private Space is enabled. Install Kejian in the main profile, remove that restriction and restart the launcher.",
    "预览即时更新。保留圆角安全区；边距过大时按尺寸缩减，避免挤掉文字。" to "The preview updates live. A safe corner area is preserved, and excessive padding is reduced for smaller widgets so text stays visible.",
    "课间已阻止本次启动闪退" to "Kejian prevented a startup crash", "本地课表和登录凭据没有被清除。请关闭后重新打开；诊断信息已保存在本机。" to "Your local schedule and sign-in credentials were not cleared. Close and reopen the app; diagnostic data has been saved on this device.", "关闭应用" to "Close app",
    "课程详情的展开与收起改用同一动画进度，文字和卡片会沿原路径一起回到表格，不再闪烁或跳变。" to "Event details now use one shared animation timeline, so the card and its text return to the grid together without flashing or jumping.",
    "新增中文 / English 完整切换，覆盖应用界面、新手引导、桌面小组件与通知提醒。" to "Added a full 中文 / English switch across the app, guide, widgets and notifications.",
    "重新设计 24 小时无安排的小组件状态，以更舒适的留白、层级和每日短句呈现。" to "Redesigned the widget's empty 24-hour state with calmer spacing, clearer hierarchy and a rotating daily line.",
    "官网同步加入会议、截止日、个人安排与双语功能介绍；课间不再只是一张课程表。" to "The website now introduces meetings, deadlines, personal plans and bilingual support. Kejian is more than a class timetable.",
    "录音转写加入受控并发队列，页面与通知栏会显示当前排队位次。" to "Recording transcription now uses a controlled queue, with your position shown in the app and notifications.",
    "转写任务保存在云端队列，服务器重启后可继续，失败不会扣除录音时长。" to "Transcription jobs persist in the cloud queue, resume after server restarts, and refund recording time on failure.",
    "新版本可以在课间内后台下载，通知栏显示进度，下载完成后可立即安装。" to "Updates can now download in the background with notification progress and an install prompt when ready.",
    "暂不安装时，设置页会持续保留“安装已下载更新”入口。" to "If you defer installation, Settings keeps an Install downloaded update button.",
    "一" to "Mon", "二" to "Tue", "三" to "Wed", "四" to "Thu", "五" to "Fri", "六" to "Sat", "日" to "Sun"
)

private val phraseEnglish=listOf(
    "课间 2.0.1 更新内容" to "What's new in Kejian 2.0.1",
    "课间 2.0.2 更新内容" to "What's new in Kejian 2.0.2",
    "录音转写接入豆包 Seed-ASR 2.0，增强课堂、中英混说、数字与专有名词的识别能力。" to "Recording transcription now uses Doubao Seed-ASR 2.0 for stronger classroom, mixed-language, numeric and proper-name recognition.",
    "转写总结启用 KJN1-SUMMARY/2 固定协议校验；格式异常会自动修正，失败不会扣除录音时长。" to "Transcription summaries now use strict KJN1-SUMMARY/2 validation, automatic format repair and automatic minute refunds on failure.",
    "Pro 月费调整为 ¥29.9，权益与每月 10120 分钟录音转写总结额度保持不变。" to "Pro is now ¥29.9 per month, with the same benefits and 1,120 monthly transcription-summary minutes.",
    "修复英文切换后部分页面未立即刷新的问题，并补齐页面、弹窗、通知与桌面小组件的英文文案。" to "Fixed pages that did not refresh immediately after switching to English, and completed English text across screens, dialogs, notifications and widgets.",
    "录音不足 10 秒时不会结束或生成无效文件，并会提示继续录制。" to "Recordings under 10 seconds now continue instead of producing invalid files, with a clear prompt to keep recording.",
    "关联课程改为课表式弹窗，完整保留主页课程模块的颜色、尺寸与信息层级。" to "Event attachment now uses a timetable dialog with the same card colors, dimensions and information hierarchy as Home.",
    "不登录也能继续使用完整课表。登录后，课表才会加密传输到 kejian.im，并可在其他设备恢复。" to "You can use the full schedule without signing in. After you sign in, it is encrypted in transit to kejian.im and can be restored on another device.",
    "AI 与录音总结：无限" to "AI and recording summaries: unlimited",
    "课表 AI：剩余 " to "Schedule AI: ",
    "录音总结：剩余 " to "recording summaries: ",
    "目标云存档已有内容。继续后会由当前本地存档替换。" to "The target cloud slot already contains a save. Continuing will replace it with the local save.",
    "本地已有课表。继续后会由所选云存档替换本机课表。" to "This device already has a schedule. Continuing will replace it with the selected cloud save.",
    "云存档 " to "Cloud save ",
    "请检查时间（如 08:10）和周次（如 1-16）" to "Check the time (for example, 08:10) and weeks (for example, 1–16).",
    "请填写有效时长，并确保与起止时间一致" to "Enter a valid duration that matches the start and end times.",
    "仅本次：" to "This occurrence: ",
    "（修改星期会调整到同一周）" to " (changing the day keeps it in the same week)",
    "请选择有效日期" to "Choose a valid date",
    "全天（不显示在时间轴）" to "All day (not shown on the time axis)",
    "截止时间 · 选填" to "Due time · optional",
    "横向滑动编辑各列；保存后应用到所有周次。" to "Swipe horizontally to edit columns. Saving applies changes to every recurrence.",
    "取消全选" to "Clear selection",
    "全选" to "Select all",
    "统一编辑" to "Edit together",
    "可用撤销恢复" to "Undo available",
    "删除所选" to "Delete selected",
    "条严格 KJ1 课程记录" to " strict KJ1 event records",
    "剪贴板没有表格文本" to "The clipboard does not contain a table",
    "粘贴导入" to "Paste to import",
    "清空文字" to "Clear text",
    "＋ 添加一行" to "+ Add row",
    "留空的字段保持原样；修改开始时间时保留原时长。" to "Blank fields stay unchanged. Changing the start time keeps the original duration.",
    "时长 · 分钟" to "Duration · minutes",
    "请填写有效的时间和正整数时长" to "Enter a valid time and a positive whole-number duration",
    "存在无效行，或结束时间超过 24:00" to "A row is invalid or its end time is after 24:00",
    "应用到所选" to "Apply to selected",
    "统一开始时间" to "Set one start time",
    "无需联网。支持 UTF-8 / UTF-16 的 CSV、TSV，以及课间 JSON 完整备份。" to "Works offline with UTF-8 / UTF-16 CSV and TSV files, plus complete Kejian JSON backups.",
    "列顺序：课程、星期、开始、结束、课堂地址、教室、颜色（0–11）、周次、教师、提醒。前四列必填；也支持严格 KJ1 行。" to "Column order: event, day, start, end, address, room, color (0–11), weeks, host/teacher and reminder. The first four are required. Strict KJ1 rows are also supported.",
    "CSV / TSV 文本" to "CSV / TSV text",
    "导入前会展示预览，不会直接写入。CSV / TSV 追加课程；JSON 恢复会替换全部数据。单次调整请通过 JSON 备份。" to "A preview is shown before anything is saved. CSV / TSV appends events; JSON restore replaces all data. Use JSON backups for occurrence changes.",
    "请使用底部“识别”专区。云端 AI 接入后会统一处理图片、PDF 与常见 Office 文件；当前文本和课间备份仍可在这里导入。" to "Use the AI tab for images, PDFs and common Office files. Text and Kejian backups can still be imported here.",
    "示例：删除周五下午的课程；把周三大学英语改到 14:00；下周五是高数作业截止日。AI 只返回固定操作，不参与聊天。" to "Examples: delete Friday afternoon events; move Wednesday English to 14:00; make next Friday the calculus assignment deadline. AI returns fixed operations and does not chat.",
    "会员与额度" to "Plans and allowances",
    "选择会员" to "Choose a plan",
    "每月 150 万 AI token、120 分钟录音转写总结、3 个云存档与完整小组件外观。" to "1.5 million AI tokens, 120 minutes of recording transcription and summaries, three cloud saves and full widget styling each month.",
    "包含 Plus 全部功能，每月 AI 额度提升至 400 万 token，录音转写总结时长提升至 1120 分钟。" to "All Plus features, with 4 million AI tokens and 1,0120 minutes of transcription and summaries each month.",
    "包含 Plus 全部权益，并将每月录音转写总结时长提升到 1120 分钟。" to "Includes every Plus benefit and raises recording transcription and summaries to 1,0120 minutes per month.",
    "Pro 可另购：¥10 / 240 分钟。基础录音和课程关联始终免费。" to "Pro members can add 240 minutes for ¥10. Basic recording and event attachment remain free.",
    "开发者账号：全部权益与额度无限。" to "Developer account: every feature and allowance is unlimited.",
    "任务结果：" to "Task result: ",
    "识别到 " to "Recognized ",
    "确认后应用新增、替换或删除结果；当前设置保持不变。" to "Confirm to apply additions, replacements and deletions. Current settings stay unchanged.",
    "完整恢复将替换当前课程、截止日及设置。" to "A complete restore replaces current events, deadlines and settings.",
    "确认后追加到课表，原有内容保留。" to "Confirm to append these items while keeping existing events.",
    "需要核对" to "need review",
    "我已核对并确认应用这次课表改动" to "I checked the preview and confirm these changes",
    "我确认用此备份替换全部课程和设置" to "I confirm this backup may replace all events and settings",
    "发现新版本 " to "New version available: ",
    "下载更新" to "Download update",
    "本地数据读取失败" to "Could not read local data",
    "为保护数据，已暂停写入。请先导出备份，再尝试恢复。" to "Saving is paused to protect your data. Export a backup before trying to restore it.",
    "导出原始数据" to "Export raw data",
    "点此管理账号；¥9.9/月可成为支持者。" to "Manage your account here. Supporter is ¥9.9/month.",
    "请填写学期名称，以及有效的周一日期" to "Enter a term name and a valid Monday date",
    "可在课前 1–120 分钟发送；课程自身的提醒开关仍需开启。" to "Send reminders 1–120 minutes early. Each event's reminder must also be enabled.",
    "准时提醒权限已允许。" to "Exact reminders are allowed.",
    "尚未允许准时提醒，系统可能延后通知。" to "Exact reminders are not allowed, so the system may delay notifications.",
    "首次安装默认关闭示例课程提醒。系统省电、强行停止和厂商后台限制可能影响送达，请在真机上验证；需要时允许课间自启动。" to "Sample-event reminders are off after installation. Battery saving, force stop and vendor background limits can delay delivery; allow Kejian to auto-start if needed.",
    "点一下，查看完整详情" to "Tap to see full details",
    "打开课间时课表处于浏览模式。点右下角「编辑」，才会出现保存、加号和周次切换。" to "Kejian opens in browse mode. Tap Edit to reveal Save, add and recurrence controls.",
    "点「＋」可完整填写课程。长按「＋」，圆形会变成课程卡片，拖到表格后松手，自动吸附到整点或半点。" to "Tap + to enter every event detail. Hold + and it becomes an event card; drag it onto the grid to snap to the hour or half-hour.",
    "点课程后，同一张卡片会从原位展开，显示完整名称、详情、时间与地点。轻触空白处，它会沿同一路径缩回表格。" to "Tap an event and the same card expands from the grid to show its name, details, time and location. Tap outside to return it along the same path.",
    "拖动时加号变成红色垃圾桶。移入后周围泛光，松手删除；误删可用「撤销」，也能「重做」。周次按钮决定只改本次还是所有周次。" to "While dragging, + becomes a red bin. Move onto it and release to delete. Undo and Redo are available, and the recurrence control chooses this occurrence or all weeks.",
    "点「批量删除」后，保存和加号淡出。拖动框选多节课程，或逐个点按切换选择；手指靠近表格边缘会自动滚动。再次点删除即可一次移除，仍可撤销。" to "Tap Batch delete, then drag around several events or tap them one by one. The grid scrolls near its edges. Tap delete again to remove the selection; Undo remains available.",
    "竖向双指调整行距，横向双指调整列距，斜向同时缩放。所有课程改动先放在草稿里，点「保存」后才更新提醒和桌面组件。" to "Pinch vertically for row height, horizontally for column width, or diagonally for both. Changes remain a draft until Save updates reminders and widgets.",
    "在编辑模式点「＋」，选择新建截止日。截止日可以独立存在，也能关联课程；保存后会出现在对应日期的顶部标记中，不会挤进 00:00 时间轴。点标记可查看详情。" to "In edit mode, tap + and choose New deadline. It may stand alone or link to an event, and appears above its date instead of at midnight. Tap the marker for details.",
    "在 AI 页上传课表图片，或输入新增、替换、删除命令。AI 只生成固定操作；软件先展示预览，你确认后才应用并显示「任务已完成！」。演示不会联网或消耗积分。" to "Upload a timetable image in AI, or type an add, replace or delete instruction. AI returns fixed operations; Kejian previews them and applies them only after confirmation. The demo uses no network or allowance.",
    "这是演示，不会修改你的日程。" to "This is a demo and will not change your schedule.",
    "备份无法读取：" to "Could not read backup: ",
    "无法打开设置，请在手机设置中找到课间 → 通知" to "Could not open Settings. Find Kejian → Notifications in system settings.",
    "已开启提醒" to "Reminders enabled",
    "已关闭提醒" to "Reminders disabled",
    "请在系统通知设置中允许课间发送通知后重新测试。" to "Allow Kejian notifications in system settings, then test again.",
    "文件超过 2 MB，请分批导入" to "The file exceeds 2 MB. Import it in smaller parts.",
    "文件无法读取" to "Could not read the file",
    "导入失败：" to "Import failed: ",
    "文件已选择；AI 服务接入后会在确认上传后开始识别。当前不会上传或扣次。" to "File selected. Recognition starts only after upload confirmation when the AI service is available. Nothing is uploaded or charged now.",
    "没有备份数据" to "No backup data found",
    "无法创建文件" to "Could not create the file",
    "完整备份已保存（含地址和单次调整）" to "Complete backup saved, including addresses and occurrence changes",
    "备份失败：" to "Backup failed: ",
    "新课程已放好，点模块 → 自定义完善课堂地址" to "The new event is placed. Tap it → Customize to add its location.",
    "当天没有足够的空闲时间，请用自定义新建到其他日期" to "There is not enough free time that day. Use Customize to create it on another date.",
    "完整备份已恢复" to "Complete backup restored",
    "导入已完成" to "Import complete",
    "课间提示" to "Kejian notice",
    "将删除所有课程及单次调整。建议先备份；清空会先进入草稿；点保存后才生效，可在编辑页撤销。" to "This removes every event and occurrence change. Consider a backup first. Clearing creates a draft that applies after Save and can be undone in the editor.",
    "课表已清空" to "Schedule cleared",
    "当前为浏览模式。点右下角编辑后，可复制、自定义或拖动课程。" to "You are in browse mode. Tap Edit to duplicate, customize or drag events.",
    "点选一项编辑" to "Tap an item to edit",
    "课程会占用时间段；截止日只标记日期整列，不会画在凌晨。" to "Events occupy a time range. Deadlines mark a date and are not drawn at midnight.",
    "账号不是使用课间的前提。你可以继续只保存在本机；也可以使用邮箱登录，在换手机时恢复课表。" to "A Kejian account is optional. Keep using local storage, or sign in with email to restore your schedule on another phone.",
    "可以更新" to "is available",
    "前往更新" to "Update now",
    "稍后" to "Later",
    "离开编辑模式？" to "Leave edit mode?",
    "还有未保存的课程改动。保存后才会更新通知和桌面组件。" to "There are unsaved event changes. Notifications and widgets update after Save.",
    "退出编辑后将恢复浏览模式。" to "Leaving edit mode returns to browse mode.",
    "保存并离开" to "Save and leave",
    "继续编辑" to "Keep editing",
    "放弃改动" to "Discard changes",
    "收起课程详情" to "Close event details",
    "列 " to "Columns ",
    " / 行 " to " / rows ",
    " · 重置" to " · Reset",
    "录音时间过短，至少需要录制 10 秒。" to "Recording is too short. Record for at least 10 seconds.",
    "支持者会员权益" to "Supporter benefits",
    "导入" to "Import",
    "开发者 · ∞" to "Developer · ∞",
    "课间 KJ1" to "Kejian KJ1",
    "请先点编辑" to "Tap Edit first",
    "已移动所有周次" to "Moved every recurrence",
    "已移动本次课程" to "Moved this occurrence",
    "已删除所有周次 · 可撤销" to "Deleted every recurrence · Undo available",
    "已删除本次课程 · 可撤销" to "Deleted this occurrence · Undo available",
    "已复制课程" to "Event duplicated",
    "课间课程 KJ1" to "Kejian event KJ1",
    "已复制严格 KJ1 课程记录" to "Strict KJ1 event record copied",
    "已删除所有周次" to "Deleted every recurrence",
    "已删除本次课程" to "Deleted this occurrence",
    "课程已创建" to "Event created",
    "已保存所有周次" to "Saved every recurrence",
    "已保存本次课程" to "Saved this occurrence",
    "截止日已删除 · 可撤销" to "Deadline deleted · Undo available",
    "表格更改已保存" to "Table changes saved",
    "组件外观已保存" to "Widget appearance saved",
    "组件透明度已保存" to "Widget opacity saved",
    "组件背景已保存" to "Widget background saved",
    "组件背景明暗已保存" to "Widget brightness saved",
    "当前桌面不支持应用内直接添加。请回到主空间，长按桌面 → 小组件 → 搜索“课间”；若仍找不到，请关闭应用锁/隐私空间后重启桌面。" to "This launcher cannot add the widget from inside the app. Return to the main profile, hold the Home screen → Widgets → search Kejian. If it is still missing, disable App Lock or Private Space and restart the launcher.",
    "已向桌面发送添加请求，请在系统窗口确认。添加成功后会收到提示。" to "The add request was sent to the launcher. Confirm it in the system dialog; Kejian will notify you when it is added.",
    "桌面拒绝了添加请求。请确认课间安装在主空间，关闭应用锁/隐私空间后，从桌面小组件列表添加。" to "The launcher rejected the request. Make sure Kejian is installed in the main profile, disable App Lock or Private Space, then add it from the widget list.",
    "无法请求添加小组件：" to "Could not request the widget: ",
    "。请尝试长按桌面手动添加。" to ". Try holding the Home screen and adding it manually.",
    "无法打开下载页，请访问 kejian.im" to "Could not open the download page. Visit kejian.im.",
    "设置已保存" to "Settings saved",
    "请在系统设置中允许“闹钟和提醒”" to "Allow Alarms & reminders in system settings",
    "课间备份-" to "Kejian-backup-",
    "AI 任务已应用" to "AI task applied",
    "录音已保存到历史" to "Recording saved to history",
    "课堂总结已保存" to "Class summary saved",
    " 更新内容" to " — What's new",
    "已保存录音 · " to "Saved recording · ",
    "当前尺寸实际留白：上 " to "Effective padding: top ",
    " / 下 " to " / bottom ",
    " / 左 " to " / left ",
    " / 右 " to " / right ",
    "在课表中点选一个课程模块" to "Tap an event card in the timetable",
    "单次录音时长应为 10 秒到 5 小时" to "Each recording must be between 10 seconds and 5 hours.",
    "课间 · 接下来 24 小时" to "KEJIAN · NEXT 24 HOURS",
    "日程之外，也要记得照顾自己。" to "Remember to take care of yourself beyond the schedule.",
    "给时间留一点空白，也是在认真生活。" to "Leaving room in the day is part of living well.",
    "休息不是停下，是为下一次出发留力。" to "Rest saves energy for what comes next.",
    "支持者会员 · ¥9.9 / 月" to "Supporter · ¥9.9 / month",
    "Plus · ¥5.99 / 月" to "Plus · ¥5.99 / month",
    "Pro · ¥29.9 / 月" to "Pro · ¥29.9 / month",
    "支持者" to "Supporter",
    "录音时间过短或保存失败" to "The recording was too short or could not be saved",
    "无法开始录音：" to "Could not start recording: ",
    "需要麦克风权限才能录音" to "Microphone permission is required to record",
    "录音已导出" to "Recording exported",
    "导出失败：" to "Export failed: ",
    "录音进行状态" to "Recording status",
    "暂停录音" to "Pause recording",
    "继续录音" to "Resume recording",
    "录音已暂停" to "Recording paused",
    "课间正在录音" to "Kejian is recording",
    "音频只保存在本机；点停止结束录音" to "Audio stays on this device. Tap Stop to finish.",
    "选择关联课程" to "Attach to an event",
    "不关联课程" to "Do not attach",
    "本月剩余" to "This month: ",
    "课堂录音" to "Class recording",
    "已完成转写" to "Transcription complete",
    "课间标志" to "Kejian logo",
    "课间启动标志" to "Kejian launch logo",
    "课程颜色" to "Event color",
    "暂时没有课程" to "No events yet",
    "24小时内暂无其他课程" to "No other events in the next 24 hours",
    "打开课间安排课程" to "Open Kejian to add an event",
    "打开添加" to "Tap to add",
    "点击添加" to "Tap to add",
    "未填地址" to "No location",
    "空闲" to "Free",
    "结束" to "ends",
    "课间小组件已添加到桌面" to "Kejian widget added to your Home screen",
    "切换后应用、小组件、提醒和引导会同步使用英文；你填写的课程名称不会被翻译。" to "The app, widgets, reminders and guide switch together. Names you entered remain unchanged.",
    "圆角 " to "Corner radius ",
    "上下左右独立调节" to "independent padding on every side",
    "当前尺寸实际留白：" to "Current effective padding: ",
    "调亮 " to "Brighter ",
    "调暗 " to "Darker ",
    "添加 " to "Add ",
    " 小组件" to " widget",
    "下一节 · " to "Next · ",
    "未来 24 小时没有课程，休息一下吧～" to "Nothing scheduled in the next 24 hours. Take a break.",
    "长按拖动 · 点保存后生效" to "Hold to drag · changes apply after Save",
    "07:00 起 · 双指调整行距/列距" to "Starts at 07:00 · pinch to adjust rows and columns",
    "拖动框选，或点按课程切换选择 · 靠近边缘自动滚动" to "Drag to select, or tap events to toggle · edge scrolling is automatic",
    "已批量删除 " to "Batch deleted ",
    " 个课程模块 · 可撤销" to " event cards · Undo available",
    "删除 " to "Delete ",
    "地点  " to "Location  ",
    "教师  " to "Host / teacher  ",
    "课堂总结  " to "Class summary  ",
    "已保存课堂录音 · " to "Saved class recording · ",
    "本月额度" to "Monthly allowance",
    "支持者会员权益" to "Supporter benefits",
    "用户头像" to "Profile photo",
    "默认头像" to "Default avatar",
    "长按拖动" to "Hold and drag",
    "空槽位 · 可拖入本地存档" to "Empty slot · drag the local save here",
    "注销云端账号？" to "Delete cloud account?",
    "云端账号和云端课表将永久删除；当前手机里的课程会保留。" to "Your cloud account and cloud schedule will be deleted permanently. Events on this device will remain.",
    "输入图中的 5 个字符" to "Enter the five characters shown",
    "正在读取…" to "Loading…",
    "失效" to "Expired",
    "课前弹窗提醒" to "Event banners",
    "用户启用的课前横幅、声音和振动提醒" to "User-enabled event banners, sound and vibration",
    "需要通知权限" to "Notification permission required",
    "系统通知已关闭" to "System notifications are off",
    "课前提醒渠道已关闭" to "Reminder channel is disabled",
    "通知分组已关闭" to "Notification group is disabled",
    "已选择弹窗提醒" to "Banners enabled",
    "测试通知已提交系统" to "Test notification submitted",
    "课前提醒已发送" to "Reminder sent",
    "通知权限被系统拒绝" to "Notification permission denied",
    "通知未能发送" to "Notification could not be sent",
    "截止提醒已发送" to "Deadline reminder sent",
    "截止提醒未能发送" to "Deadline reminder could not be sent",
    "课间测试通知" to "Kejian test notification",
    "截止时间" to "Due",
    "当前是普通/静默渠道，不能弹出横幅。可点“启用弹窗提醒”或在系统渠道设置中提高重要性。" to "This channel is silent or normal, so banners cannot appear. Enable banners or raise its priority in system settings.",
    "当前开启勿扰，系统可能抑制弹窗与声音。" to "Do Not Disturb may suppress banners and sound.",
    "已设为高优先级，但渠道无提示音；部分手机还需开启声音和悬浮通知。" to "High priority is enabled, but the channel has no sound. Some phones also require floating notifications.",
    "已使用高优先级渠道；请同时允许系统“悬浮通知 / 横幅”。" to "High-priority reminders are active. Also allow floating notifications or banners in system settings.",
    "课间 2.0.0 更新内容" to "What's new in Kejian 2.0.0",
    "课间 1.9.2 更新内容" to "What's new in Kejian 1.9.2",
    "24小时内没有课程，休息一下吧~" to "Nothing in the next 24 hours. Take a little break.",
    "未来 24 小时没有课程，休息一下吧～" to "Nothing in the next 24 hours. Take a little break.",
    "下一节" to "Next", "正在上课" to "In progress",
    "已保存" to "Saved", "已创建" to "Created", "已删除" to "Deleted", "已复制" to "Duplicated", "可撤销" to "Undo available",
    "节课程" to " events", "个截止日" to " deadlines", "项" to " items", "云存档" to "Cloud save", "槽位" to "Slot",
    "任务已完成！" to "Task completed!", "正在识别版面与课程信息…" to "Reading the layout and event details…",
    "提示：" to "Note: ", "课堂地址：" to "Location: ", "老师：" to "Teacher: ", "地点  " to "Location  ", "教师  " to "Teacher  ",
    "项需要核对" to " items need review", "组时间重叠" to " time overlaps", "周次：" to "Weeks: ",
    "本月剩余 " to "This month: ", " 分钟" to " min left", "建议关联：" to "Suggested: ", "暂不关联课程" to "No event selected", "保存到「" to "Save to “", "」" to "”", "已保存录音 · " to "Saved recording · ",
    "录音已保存到历史" to "Recording saved to history", "录音已关联课程" to "Recording attached to event", "课堂总结已保存" to "Summary saved", "正在上传并转写。服务器处理结束后会立即删除音频…" to "Uploading for transcription. The temporary server copy will be deleted when processing ends…", "转写与总结完成，请选择课程并保存" to "Transcription and summary are ready. Choose an event or save independently.",
    "查看课程总结" to "View class summary", "查看已保存录音" to "View saved recording", "逐字稿" to "Transcript", "重点" to "Key points", "待办" to "Action items",
    "后台处理" to "Background processing", "文件转换、AI 转写与总结的进度" to "File conversion, transcription and summary progress",
    "课间正在后台处理" to "Kejian is working in the background", "可以离开此页面，完成后会通知你" to "You can leave this page. We will notify you when it is ready.",
    "课堂总结已完成" to "Class summary is ready", "打开课间预览总结并选择关联课程" to "Open Kejian to review the summary and attach it to an event",
    "转写总结未完成" to "Transcription did not finish", "课表文件识别完成" to "Schedule file recognition is ready", "打开课间核对识别预览" to "Open Kejian to review the recognition preview", "文件处理未完成" to "File processing did not finish",
    "正在手机本地转换文件，随后自动上传" to "Converting the file on this device, then uploading automatically", "录音已上传，正在后台转写总结" to "Recording uploaded; transcribing and summarizing in the background",
    "后台处理中" to "In background", "这节课只保存了本地录音。" to "This event only has a local recording.",
    "今天" to "Today", "明天" to "Tomorrow", "全天" to "All day", "截止日" to "deadline"
)

fun localized(value:String,english:Boolean=AppLanguage.english):String {
    if(!english||value.isBlank())return value
    exactEnglish[value]?.let {return it}
    phraseEnglish.firstOrNull {it.first==value}?.let {return it.second}
    var out=value
    out=out.replace(Regex("(\\d+) 月 (\\d+) 日")){"${it.groupValues[1]}/${it.groupValues[2]}"}
    out=out.replace(Regex("周([一二三四五六日])")){mapOf("一" to "Mon","二" to "Tue","三" to "Wed","四" to "Thu","五" to "Fri","六" to "Sat","日" to "Sun")[it.groupValues[1]]!!}
    out=out.replace(Regex("第\\s*(\\d+)\\s*周")){"Week ${it.groupValues[1]}"}
    out=out.replace(Regex("(\\d+)\\s*节课程")){"${it.groupValues[1]} events"}
    out=out.replace(Regex("(\\d+)\\s*节课")){"${it.groupValues[1]} events"}
    out=out.replace(Regex("(\\d+)\\s*个截止日")){"${it.groupValues[1]} deadlines"}
    out=out.replace(Regex("保存\\s*(\\d+)\\s*行")){"Save ${it.groupValues[1]} rows"}
    out=out.replace(Regex("已删除\\s*(\\d+)\\s*行，可用撤销恢复")){"Deleted ${it.groupValues[1]} rows · Undo available"}
    out=out.replace(Regex("统一编辑\\s*(\\d+)\\s*节课")){"Edit ${it.groupValues[1]} events together"}
    out=out.replace(Regex("有\\s*(\\d+)\\s*组时间重叠，保存时会再次确认。")){"${it.groupValues[1]} time overlaps will be confirmed again when saving."}
    out=out.replace(Regex("(\\d+)\\s*分钟")){"${it.groupValues[1]} min"}
    phraseEnglish.forEach {(zh,en)->out=out.replace(zh,en)}
    if(out.startsWith("课间 "))out="Kejian "+out.removePrefix("课间 ")
    return out
}

@Composable
fun Text(
    text:String,
    modifier:Modifier=Modifier,
    color:Color=Color.Unspecified,
    fontSize:TextUnit=TextUnit.Unspecified,
    fontStyle:FontStyle?=null,
    fontWeight:FontWeight?=null,
    fontFamily:FontFamily?=null,
    letterSpacing:TextUnit=TextUnit.Unspecified,
    textDecoration:TextDecoration?=null,
    textAlign:TextAlign?=null,
    lineHeight:TextUnit=TextUnit.Unspecified,
    overflow:TextOverflow=TextOverflow.Clip,
    softWrap:Boolean=true,
    maxLines:Int=Int.MAX_VALUE,
    minLines:Int=1,
    onTextLayout:((TextLayoutResult)->Unit)?=null,
    style:TextStyle=androidx.compose.material3.LocalTextStyle.current
){
    androidx.compose.material3.Text(text=localized(text),modifier=modifier,color=color,fontSize=fontSize,fontStyle=fontStyle,fontWeight=fontWeight,fontFamily=fontFamily,letterSpacing=letterSpacing,textDecoration=textDecoration,textAlign=textAlign,lineHeight=lineHeight,overflow=overflow,softWrap=softWrap,maxLines=maxLines,minLines=minLines,onTextLayout=onTextLayout,style=style)
}
